name: "demo-auth-aut"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KC_HTTP_PORT: 9081
      KEYCLOAK_ADMIN: admin # A remplacer par un secret au passage en production
      KEYCLOAK_ADMIN_PASSWORD: admin # A remplacer par un secret au passage en production
    ports:
      - 9081:9081
    volumes:
      - ./realm-config/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm' # A utiliser en développement seulement

  client:
    build:
      context: ./client
    ports:
      - 4200:4200
